### ISSUE TITLE
A Number of Problems of Varying Severity

### ISSUE THREAD

**Issue by replacem3nts** [learn-co-curriculum/active-record-associations-quiz#2]
**README Line 23** - Question 3 of the quiz is improperly worded.  Fist line says, "A Pokémon trainer can hone their Pokémons' skills at a gym. Each Pokémon trainer can train at multiple gyms." For a question asking about a quantifiable relationship (1 : 1, 1 : many) this presents problems because: sentence one says, "A Pokemon trainer" implying we are still talking about only one trainer;  sentence two says, "Each Pokemon trainer" implying we are talking about the universe of Pokemon trainers (multiple). Simple fix would be to change second sentence to also say "A Pokemon trainer." Screenshot below.

<img width="982" alt="Screen Shot 2020-03-21 at 11 52 26 AM" src="https://user-images.githubusercontent.com/57644669/77230599-b9bc0080-6b6b-11ea-919e-9ff2a4e7856a.png">

**README line 78** - Question 5 contains a typo in the last sentence of the text block. Change "therefor" to "therefore." Screenshot below.

<img width="982" alt="Screen Shot 2020-03-21 at 11 52 57 AM" src="https://user-images.githubusercontent.com/57644669/77230649-17e8e380-6b6c-11ea-94d4-e58160c1eec1.png">

**README line 101** - The final answer to question 5 contains extraneous comment code from a past revision. The fact that it renders in the learn platform appears to be a mistake. Screenshot below.

<img width="957" alt="Screen Shot 2020-03-21 at 11 55 19 AM" src="https://user-images.githubusercontent.com/57644669/77230906-0a345d80-6b6e-11ea-8864-4e6573b5d7be.png">

**README line 114** - Question 7 is problematic in so many ways, it's difficult to see how to change it to so that it actually tests anything substantive. 1. The second sentence specifies that all the Pokemon in the list are water type, which implies that all answers are correct.  2. The answer choices contain the names of Pokemon and no other information--the student is left to infer type from the names and match with "water type." 3. Based on all of the above, the code snippet above the text doesn't add any useful information. In sum, this question seems to test the student's ability to ignore sentence two and perform basic pattern matching of names and "water type." Screenshot below.

<img width="502" alt="Screen Shot 2020-03-21 at 11 53 55 AM" src="https://user-images.githubusercontent.com/57644669/77230831-837f8080-6b6d-11ea-913f-989656132f7e.png">

**Comment by sylwiavargas** [comment]
@replacem3nts thank you for drawing our attention to these issues. We've fixed them all! The frustrating question 7 is no longer a part of the quiz. Thank you!

**Comment by replacem3nts** [comment]
> @replacem3nts thank you for drawing our attention to these issues. We've fixed them all! The frustrating question 7 is no longer a part of the quiz. Thank you!

On behalf of all future students to take the quiz, thank you!
