### ISSUE TITLE
Answer Seems Incorrect

### ISSUE THREAD

**Issue by chadpalmer2** [learn-co-curriculum/active-record-associations-quiz#3]
Question 3 asks what the relationship between a trainer and a gym would be. A trainer can train at many gyms, and gyms can host many trainers, so the relationship should be many-many. The question states that the correct answer, however, is one-to-many.

Question 8 is ambiguous.

**Comment by helloRupa** [comment]
Resolved in PR: https://github.com/learn-co-curriculum/active-record-associations-quiz/pull/4
